Repository CodeForAfrica/PromiseTracker, pull requests merged in 2021-01, with the labels that each got.

#225 [Chore] Dependencies
  package.json
  yarn.lock
Labels: dependencies

#222 [Chore] Multiple node query
  src/lib/check/gql/GET_PROMISE.js
  src/lib/check/index.js
  src/pages/promises/[...slug].js
Labels: chore

#226 [Fix] Render multiple charts
  src/components/PromiseChart/index.js
  src/components/PromiseChart/useStyles.js
  src/lib/check/index.js
Labels: bug
