Repository CodeForAfrica/PromiseTracker, pull requests merged in 2021-08, with the labels that each got.

#348 [Chore] Dependencies
  package.json
  yarn.lock
Labels: dependencies

#347 Adds multi promise sources
  public/promises.json
  src/lib/api.js
  src/lib/jsonSource/index.js
  src/lib/jsonSource/jsonSourceClient.js
  src/pages/index.js
  src/pages/promises/[...slug].js
  src/pages/promises/index.js
Labels: enhancement

#349 [Feature] gSheet
  .env.template
  .gitignore
  package.json
  public/data/.keep
  public/promises.json
  src/components/Dataset/index.js
  src/components/Hero/ProfileChart/DesktopChart/index.js
  src/components/Hero/ProfileChart/MobileChart/index.js
  src/components/Hero/ProfileChart/ProfileDetails.js
  src/components/Hero/ProfileChart/RectChart/index.js
  src/components/Hero/index.js
  src/components/KeyPromises/KeyPromise.js
  src/components/KeyPromises/useStyles.js
  src/components/PromiseTimeline/index.js
  src/components/Promises/index.js
  src/config.js
  src/lib/actnow/index.js
  src/lib/backend/index.js
  src/lib/cache/index.js
  src/lib/gsheets/index.js
  src/lib/jsonSource/index.js
  src/lib/jsonSource/jsonSourceClient.js
  src/lib/jsonql/promises.js
  src/lib/pc/index.js
  src/lib/server/index.js
  src/lib/wp/index.js
  src/pages/analysis/petitions/[slug].js
  src/pages/index.js
  src/pages/promises/[...slug].js
  src/pages/promises/index.js
  src/theme/index.js
  src/utils.js
  yarn.lock
Labels: bug, enhancement, dependencies, chore, feature
