Repository CodeForAfrica/PromiseTracker, pull requests merged in 2021-02, with the labels that each got.

#242 [Feedback Fix]Change border color
  src/components/Navigation/MobileNavigation/NavigationList.js
  src/components/PromiseTimeline/TimelineEvent.js
Labels: bug, enhancement

#243 [Feedback Fix]Add resources page
  src/pages/analysis/resources.js
Labels: bug, enhancement

#244 [Feedback Fix] Hover on share button
  src/components/Share/index.js
  src/components/Share/useStyles.js
Labels: bug, enhancement

#245 [Feedback Fix]Update promise sidebar
  src/components/Promise/Radar.js
  src/components/Promise/index.js
  src/components/Promise/useStyles.js
Labels: bug, enhancement

#252 [Feedback Fix] Update site statuses
  src/components/Hero/ProfileChart/DesktopChart/index.js
  src/components/Hero/ProfileChart/MobileChart/MobileSvgChart.js
  src/components/Hero/ProfileChart/MobileChart/ProgressChart.js
  src/components/Hero/ProfileChart/MobileChart/index.js
  src/components/Hero/ProfileChart/ProfileDetails.js
  src/components/Hero/ProfileChart/RectChart/RectSvgChart.js
  src/components/Hero/ProfileChart/RectChart/index.js
  src/config.js
  src/lib/check/index.js
  src/theme/index.js
Labels: bug, enhancement

#254 [Feedback Fix] Replace Pixilated images
  src/components/ActNow/index.js
  src/components/ErrorPage/index.js
  src/components/Newsletter/index.js
  src/pages/act-now.js
Labels: bug

#262 [Chore] Dependenices
  yarn.lock
Labels: dependencies

#204 Fix/options cms wp
  src/components/Promises/index.js
  src/lib/check/gql/GET_PROJECT_META.js
  src/lib/check/index.js
  src/lib/wp/index.js
  src/pages/index.js
  src/pages/promises/[...slug].js
  src/pages/promises/index.js
Labels: enhancement

#253 [Feedback Fix] Update promise filter
  src/components/Promises/Filter/FilterButton.js
  src/components/Promises/Filter/useStyles.js
  src/components/Promises/Sort.js
  src/components/Promises/index.js
  src/components/Promises/useStyles.js
Labels: bug

#264 Fix pixilated images
  src/components/Article/index.js
  src/lib/wp/index.js
  src/pages/analysis/articles/[slug].js
Labels: bug

#276 [Fix] Server & Check Defaults
  src/lib/check/index.js
  src/lib/server/index.js
Labels: bug
