Repository CodeForAfrica/PromiseTracker, pull requests merged in 2021-07, with the labels that each got.

#341 [Feature] actNOW Registration
  .env.template
  package.json
  src/components/ActNowPage/index.js
  src/components/Form/Input.js
  src/components/Form/Label.js
  src/components/Form/useStyles.js
  src/components/IndividualRegistrationDialog/index.js
  src/components/IndividualRegistrationDialog/useStyles.js
  src/components/IndividualRegistrationForm/Form.js
  src/components/IndividualRegistrationForm/index.js
  src/components/IndividualRegistrationForm/useStyles.js
  src/pages/act-now.js
  src/pages/api/accounts/index.js
  yarn.lock
Labels: dependencies, enhancement, feature

#343 [Feature] Registration Dialog
  src/components/ActNowPage/index.js
  src/components/ActionDialog/index.js
  src/components/ActionDialog/useStyles.js
  src/components/IndividualRegistrationDialog/index.js
  src/components/RegistrationDialog/index.js
  src/components/RegistrationDialog/useStyles.js
  src/pages/act-now.js
Labels: enhancement

#344 [HotFix] actNOW API path
  src/components/IndividualRegistrationForm/index.js
  src/pages/api/accounts/index.js
Labels: bug

#342 Ft ActNow Summary
  src/components/ActNowPage/index.js
  src/components/ActNowPage/useStyles.js
  src/components/ActNowSummary/index.js
  src/components/SuggestPromise/index.js
  src/components/SuggestPromise/useStyles.js
  src/pages/act-now.js
Labels: enhancement, feature

#345 [Feature] `/analysis/petitions`
  src/components/PetitionCard/index.js
  src/components/Petitions/index.js
  src/components/PromiseStatus/index.js
  src/config.js
  src/pages/analysis/petitions/index.js
Labels: enhancement, feature

#346 [Feature] Petitions API
  src/components/PetitionCard/index.js
  src/config.js
  src/lib/actnow/index.js
  src/pages/analysis/petitions/index.js
  src/pages/api/accounts/index.js
Labels: enhancement, feature
