Repository CodeForAfrica/PromiseTracker, pull requests merged in 2021-04, with the labels that each got.

#332 [Chore] Dependencies
  .eslintrc.json
  .husky/.gitignore
  .husky/pre-commit
  next.config.js
  package.json
  yarn.lock
Labels: chore, dependencies

#309 Act Now Buttons
  src/components/ActNowCard/BaseContent.js
  src/components/ActNowCard/ConnectCard.js
  src/components/ActNowCard/FollowCard.js
  src/components/ActNowCard/PetitionCard.js
  src/components/ActNowCard/ShareCard.js
  src/components/ActNowCard/cards.js
  src/components/ActNowCard/index.js
  src/components/ActNowCard/useStyles.js
  src/components/FormDialog/UpdateDialog.js
  src/components/FormDialog/UpdateForm.js
  src/components/Promise/index.js
  src/lib/wp/index.js
  src/pages/promises/[...slug].js
Labels: enhancement

#335 [Chore] Switch gitsubmodule to http(s)
  .gitmodules
  src/pages/promises/[...slug].js
Labels: chore
