Repository CodeForAfrica/PromiseTracker, pull requests merged in 2022-02, with the labels that each got.

#358 Handle Promise Sort
  src/components/Promises/index.js
Labels: enhancement

#357 [Feature] Radar from CMS
  .env.template
  src/components/PostCardGrid/index.js
  src/components/Promise/Radar.js
  src/components/Promise/RelatedFactChecks.js
  src/components/Promise/index.js
  src/lib/gsheets/index.js
Labels: enhancement

#359 [hotfix] Show promise page header
  src/pages/promises/[...slug].js
Labels: enhancement

#360 [Chore] Next 12
  package.json
  src/components/AboutPage/index.js
  src/components/ActNowCard/BaseContent.js
  src/components/ActNowCard/ConnectCard.js
  src/components/ActNowCard/FollowCard.js
  src/components/ActNowCard/PetitionCard.js
  src/components/ActNowCard/ShareCard.js
  src/components/ActNowCard/index.js
  src/components/ActNowPage/index.js
  src/components/Footer/index.js
  src/components/Hero/ProfileChart/ProfileDetails.js
  src/components/KeyPromises/index.js
  src/components/Navigation/DesktopNavigation/index.js
  src/components/Navigation/MobileNavigation/NavigationList.js
  src/components/Navigation/MobileNavigation/index.js
  src/components/Promise/Narative.js
  src/components/PromiseTimeline/Labels.js
  src/components/PromiseTimeline/PromiseEvent.js
  src/components/Share/index.js
  src/lib/check/createApolloClient.js
  src/lib/check/index.js
  yarn.lock
Labels: bug, dependencies, chore

#361 [Feature] Related articles
  .env.template
  src/lib/gsheets/index.js
  src/lib/jsonql/promises.js
  src/pages/promises/[...slug].js
Labels: enhancement

#367 [Feature] Add image overlay and Border
  src/components/Promise/index.js
  src/components/Promise/useStyles.js
  src/pages/promises/[...slug].js
Labels: enhancement

#370 [Feature] Start/Join a Petition re-direct
  src/components/ActNowCard/PetitionCard.js
Labels: enhancement

#365 [Feature] Petition Page.
  package.json
  scripts/commons-ui-add.js
  src/components/Petition/ShareCard.js
  src/components/Petition/index.js
  src/components/Petition/useStyles.js
  src/components/PetitionCard/index.js
  src/components/SignPetition/index.js
  src/components/SignPetition/useStyles.js
  src/lib/actnow/index.js
  src/pages/analysis/petitions/[slug].js
  src/pages/promises/[...slug].js
  yarn.lock
Labels: enhancement

#371 [Fix] Navigation, Promises, Promise
  src/components/Navigation/DesktopNavigation/index.js
  src/components/PostCardGrid/index.js
  src/components/PostCardGrid/useStyles.js
  src/components/Promise/useStyles.js
Labels: bug

#372 [Fix] Empty Cetegories
  src/pages/promises/index.js
Labels: bug
